name: Python CI Pipeline

# Trigger on push or PR to the development branch
on:
  push:
    branches:
      - development  # Trigger on pushes to 'development'
  pull_request:
    branches:
      - development  # Trigger on pull requests targeting 'development'

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Set your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies from 'requirements.txt'

      # Step 4: Run tests using pytest
      - name: Run tests
        run: venv/bin/pytest -v tests  # Run tests from the 'tests' directory

 