name: Python CI Pipeline

# Trigger the workflow on push to the main branch or pull requests targeting it
on:
  push:
    branches:
      - main  # Trigger on pushes to 'main'
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main'

jobs:
  # Job 1: Set up Python environment, install dependencies, and run tests
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Set your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          python "Processing..."
          pip install -r requirements.txt  # Install dependencies from 'requirements.txt'

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          source venv/bin/activate  # Activate the virtual environment again
          pytest  # Run the tests with pytest
