name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the 'main' branch

jobs:
  # Job 1: CI - Install dependencies and run tests
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify the version of Python you want to use

      - name: Install Dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate  # Activate the virtual environment again
          pytest  # Run the tests using pytest

  # Job 2: CD - Deploy to production (optional, depending on your use case)
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test  # This job runs after the build_and_test job
    if: github.ref == 'refs/heads/main'  # Only deploy when the 'main' branch is updated

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          # Replace with your deployment commands (e.g., upload files, trigger deployment)
          echo "Deploying to production"
